%macro dbload (DBtable, DSname);
/* append new data */
 Proc Append Force base=nbs_rdb.&DBtable data=&DSname;
 Run;
 Quit;
%mend dbload;
PROC DATASETS LIB=WORK MEMTYPE=DATA
		KILL;
RUN;
QUIT; 
options fmtsearch=(nbsfmt);
 %macro assign_additional_key (ds, key);
 data &ds;
  if &key=1 then output;
  set &ds;
	&key+1;
	output;
 run;
%mend assign_additional_key;
%macro CASE_MANAGEMENT;
PROC SQL;
CREATE TABLE CASE_MANAGEMENT_INIT AS SELECT
	CASE_MANAGEMENT.CASE_MANAGEMENT_UID,
	CASE_MANAGEMENT.PUBLIC_HEALTH_CASE_UID,
	PUBLIC_HEALTH_CASE.ADD_USER_ID as ADD_USER_ID 'ADD_USER_ID',
	OOJ_INITG_AGNCY_OUTC_SNT_DATE AS OOJ_INITG_AGNCY_OUTC_SNT_DATE 'OOJ_INITG_AGNCY_OUTC_SNT_DATE',
	INIT_FOLL_UP as INIT_FOLL_UP_CODE 'INIT_FOLL_UP_CODE',
	INIT_FOLL_UP_CLOSED_DATE AS INIT_FUP_CLOSED_DT 'INIT_FUP_CLOSED_DT',
	INTERNET_FOLL_UP as INTERNET_FOLL_UP_CODE 'INTERNET_FOLL_UP_CDOE',
	INIT_FOLL_UP_NOTIFIABLE as INIT_FOLL_UP_NOTIFIABLE_CODE 'INIT_FOLL_UP_NOTIFIABLE_CODE',
	INIT_FOLL_UP_CLINIC_CODE AS INIT_FUP_CLINIC_CODE 'INIT_FUP_CLINIC_CODE',
	SURV_ASSIGNED_DATE AS SURV_INVESTIGATOR_ASSGN_DT 'SURV_INVESTIGATOR_ASSGN_DT',
	SURV_CLOSED_DATE AS SURV_CLOSED_DT 'SURV_CLOSED_DT',
	SURV_PROVIDER_CONTACT as SURV_PROVIDER_CONTACT_CODE 'SURV_PROVIDER_CONTACT_CODE',
	SURV_PROV_EXM_REASON as SURV_PROV_EXM_REASON 'SURV_PROV_EXM_REASON',
	SURV_PROV_DIAGNOSIS AS SURV_PROVIDER_DIAGNOSIS 'SURV_PROVIDER_DIAGNOSIS',
	SURV_PATIENT_FOLL_UP as SURV_PATIENT_FOLL_UP 'SURV_PATIENT_FOLL_UP',
	STATUS_900 as ADI_900_STATUS_CD 'ADI_900_STATUS_CD',
	EHARS_ID AS ADI_EHARS_ID 'ADI_EHARS_ID',
	SUBJ_HEIGHT AS ADI_HEIGHT 'ADI_HEIGHT',
	SUBJ_HEIGHT AS ADI_HEIGHT_LEGACY_CASE 'ADI_HEIGHT_LEGACY_CASE',
	SUBJ_SIZE_BUILD AS ADI_SIZE_BUILD 'ADI_SIZE_BUILD',
	SUBJ_HAIR AS ADI_HAIR 'ADI_HAIR',
	SUBJ_COMPLEXION AS ADI_COMPLEXION 'ADI_COMPLEXION',
	SUBJ_OTH_IDNTFYNG_INFO AS ADI_OTHER_IDENTIFYING_INFO 'ADI_OTHER_IDENTIFYING_INFO',
	FIELD_RECORD_NUMBER AS FL_FUP_FIELD_RECORD_NUM 'FL_FUP_FIELD_RECORD_NUM',
	FOLL_UP_ASSIGNED_DATE AS FL_FUP_INVESTIGATOR_ASSGN_DT 'FL_FUP_INVESTIGATOR_ASSGN_DT',
	INIT_FOLL_UP_ASSIGNED_DATE AS FL_FUP_INIT_ASSGN_DT 'FL_FUP_INIT_ASSGN_DT',
	FLD_FOLL_UP_PROV_EXM_REASON AS FLD_FOLL_UP_PROV_EXM_REASON 'FLD_FOLL_UP_PROV_EXM_REASON',
	FLD_FOLL_UP_PROV_DIAGNOSIS AS FLD_FOLL_UP_PROV_DIAGNOSIS 'FLD_FOLL_UP_PROV_DIAGNOSIS',
	FLD_FOLL_UP_NOTIFICATION_PLAN AS FLD_FOLL_UP_NOTIFICATION_PLAN 'FLD_FOLL_UP_NOTIFICATION_PLAN',
	FLD_FOLL_UP_EXPECTED_IN AS FLD_FOLL_UP_EXPECTED_IN 'FLD_FOLL_UP_EXPECTED_IN',
	FLD_FOLL_UP_EXPECTED_DATE AS FL_FUP_EXPECTED_DT 'FL_FUP_EXPECTED_DT',
	FLD_FOLL_UP_EXAM_DATE AS FL_FUP_EXAM_DT 'FL_FUP_EXAM_DT',
	FLD_FOLL_UP_DISPO as FL_FUP_DISPOSITION_CD 'FL_FUP_DISPOSITION_CD',
	FLD_FOLL_UP_DISPO_DATE AS FL_FUP_DISPO_DT 'FL_FUP_DISPO_DT',
	ACT_REF_TYPE_CD AS ACT_REF_TYPE_CD 'ACT_REF_TYPE_CD',
	CASE_REVIEW_STATUS AS CASE_REVIEW_STATUS 'CASE_REVIEW_STATUS',
	CASE_REVIEW_STATUS_DATE AS CASE_REVIEW_STATUS_DATE 'CASE_REVIEW_STATUS_DATE',
	INPUT(FLD_FOLL_UP_INTERNET_OUTCOME, $10.) AS FLD_FOLL_UP_INTERNET_OUT_CD 'FLD_FOLL_UP_INTERNET_OUT_CD',
	OOJ_AGENCY AS OOJ_AGENCY 'OOJ_AGENCY',
	OOJ_NUMBER AS OOJ_NUMBER 'OOJ_NUMBER',
	OOJ_DUE_DATE AS OOJ_DUE_DATE 'OOJ_DUE_DATE',
	FIELD_FOLL_UP_OOJ_OUTCOME AS FIELD_FOLL_UP_OOJ_OUTCOME 'FIELD_FOLL_UP_OOJ_OUTCOME',
	INTERVIEW_ASSIGNED_DATE AS CA_INTERVIEWER_ASSIGN_DT 'CA_INTERVIEWER_ASSIGN_DT',
	INIT_INTERVIEW_ASSIGNED_DATE AS CA_INIT_INTVWR_ASSGN_DT 'CA_INIT_INTVWR_ASSGN_DT',
	EPI_LINK_ID AS EPI_LINK_ID 'EPI_LINK_ID',
	PAT_INTV_STATUS_CD AS PAT_INTV_STATUS_CD 'PAT_INTV_STATUS_CD',
	CASE_CLOSED_DATE AS CC_CLOSED_DT 'CC_CLOSED_DT',
	INITIATING_AGNCY as INITIATING_AGNCY 'INITIATING_AGNCY',
	OOJ_INITG_AGNCY_RECD_DATE AS OOJ_INITG_AGNCY_RECD_DATE 'OOJ_INITG_AGNCY_RECD_DATE',
	OOJ_INITG_AGNCY_OUTC_DUE_DATE AS OOJ_INITG_AGNCY_OUTC_DUE_DATE 'OOJ_INITG_AGNCY_OUTC_DUE_DATE'
FROM NBS_ODS.CASE_MANAGEMENT
LEFT OUTER JOIN NBS_ODS.PUBLIC_HEALTH_CASE 
ON CASE_MANAGEMENT.PUBLIC_HEALTH_CASE_UID =PUBLIC_HEALTH_CASE.PUBLIC_HEALTH_CASE_UID;
QUIT;

DATA CASE_MANAGEMENT_INIT(RENAME=(INTERNET_FOLL_UP_CODE=INIT_FUP_INTERNET_FOLL_UP_CD 
INIT_FOLL_UP_CODE =INIT_FUP_INITIAL_FOLL_UP_CD 
SURV_PROVIDER_CONTACT_CODE=SURV_PROVIDER_CONTACT_CD
INIT_FOLL_UP_NOTIFIABLE_CODE=INIT_FUP_NOTIFIABLE_CD
FLD_FOLL_UP_INTERNET_OUT_CD=FL_FUP_INTERNET_OUTCOME_CD
/*STATUS_900=ADI_900_STATUS_CD*/
)); 
SET CASE_MANAGEMENT_INIT;

INIT_FUP_INITIAL_FOLL_UP=PUT(INIT_FOLL_UP_CODE,$CM_CIND.);

FL_FUP_EXPECTED_IN_IND=PUT(FLD_FOLL_UP_EXPECTED_IN,$YN.);
INTERNET_FOLL_UP=PUT(INTERNET_FOLL_UP_CODE,$YN.);
FL_FUP_PROV_EXM_REASON=PUT(FLD_FOLL_UP_PROV_EXM_REASON,$CM_P_RS.);
SURV_PROVIDER_EXAM_REASON=PUT(SURV_PROV_EXM_REASON,$CM_P_RS.);
/*INIT_FUP_INITIAL_FOLL_UP_CD=PUT(INIT_FOLL_UP,$CM_CIND.);*/
CA_PATIENT_INTV_STATUS=PUT(PAT_INTV_STATUS_CD,$CM_INTS.);
INITIATING_AGNCY=PUT(INITIATING_AGNCY,$CM_OOJL.);
FL_FUP_ACTUAL_REF_TYPE=PUT(ACT_REF_TYPE_CD,$CM_N_MTD.);
FL_FUP_OOJ_OUTCOME=PUT(FIELD_FOLL_UP_OOJ_OUTCOME,$NBS173F.);
FL_FUP_DISPOSITION_DESC=PUT(FL_FUP_DISPOSITION_CD,$NBS173F.);
SURV_PROVIDER_CONTACT=PUT(SURV_PROVIDER_CONTACT_CODE,$CM_P_OC.);
OOJ_AGENCY=PUT(OOJ_AGENCY,$CM_OOJL.);
FL_FUP_INTERNET_OUTCOME=PUT(FLD_FOLL_UP_INTERNET_OUT_CD,$CM_I_OC.);
FL_FUP_PROV_DIAGNOSIS=PUT(FLD_FOLL_UP_PROV_DIAGNOSIS,$R_NBS166F.);
INIT_FOLL_UP_NOTIFIABLE=PUT(INIT_FOLL_UP_NOTIFIABLE_CODE,$CM_NOTF.);
STATUS_900=PUT(ADI_900_STATUS_CD,$CM_900S.);
SURV_PATIENT_FOLL_UP_CD=PUT(SURV_PATIENT_FOLL_UP,$CM_S_PF.);
FL_FUP_NOTIFICATION_PLAN_CD=PUT(FLD_FOLL_UP_NOTIFICATION_PLAN,$CM_NP.);

RUN;
PROC SQL;
CREATE TABLE 
S_CASE_MANAGEMENT AS SELECT CASE_MANAGEMENT_INIT.*, INVESTIGATION.INVESTIGATION_KEY, INVESTIGATION.CASE_OID
FROM CASE_MANAGEMENT_INIT, NBS_RDB.INVESTIGATION 
WHERE CASE_MANAGEMENT_INIT.PUBLIC_HEALTH_CASE_UID=INVESTIGATION.CASE_UID;
QUIT;
%ASSIGN_ADDITIONAL_KEY (S_CASE_MANAGEMENT, D_CASE_MANAGEMENT_KEY);
PROC SQL;
DROP TABLE NBS_RDB.S_CASE_MANAGEMENT;
DROP TABLE NBS_RDB.L_CASE_MANAGEMENT;
CREATE TABLE L_CASE_MANAGEMENT AS SELECT D_CASE_MANAGEMENT_KEY, CASE_MANAGEMENT_UID FROM S_CASE_MANAGEMENT;
QUIT;
PROC SQL;
CREATE TABLE NBS_RDB.L_CASE_MANAGEMENT AS SELECT * FROM L_CASE_MANAGEMENT;
CREATE TABLE NBS_RDB.S_CASE_MANAGEMENT AS SELECT 
ACT_REF_TYPE_CD,
ADD_USER_ID,
ADI_900_STATUS_CD,
ADI_COMPLEXION,
ADI_EHARS_ID,
ADI_HAIR,
ADI_HEIGHT,
ADI_HEIGHT_LEGACY_CASE,
ADI_OTHER_IDENTIFYING_INFO,
ADI_SIZE_BUILD,
CA_INIT_INTVWR_ASSGN_DT,
CA_INTERVIEWER_ASSIGN_DT,
CA_PATIENT_INTV_STATUS,
CASE_OID,
CASE_REVIEW_STATUS,
CASE_REVIEW_STATUS_DATE,
CC_CLOSED_DT,
EPI_LINK_ID,
FIELD_FOLL_UP_OOJ_OUTCOME,
FL_FUP_ACTUAL_REF_TYPE,
FL_FUP_DISPO_DT,
FL_FUP_DISPOSITION_CD,
FL_FUP_DISPOSITION_DESC,
FL_FUP_EXAM_DT,
FL_FUP_EXPECTED_DT,
FL_FUP_EXPECTED_IN_IND,
FL_FUP_FIELD_RECORD_NUM,
FL_FUP_INIT_ASSGN_DT,
FL_FUP_INTERNET_OUTCOME,
FL_FUP_INTERNET_OUTCOME_CD,
FL_FUP_INVESTIGATOR_ASSGN_DT,
FL_FUP_NOTIFICATION_PLAN_CD,
FL_FUP_OOJ_OUTCOME,
FL_FUP_PROV_DIAGNOSIS,
FL_FUP_PROV_EXM_REASON,
FLD_FOLL_UP_EXPECTED_IN,
FLD_FOLL_UP_NOTIFICATION_PLAN,
FLD_FOLL_UP_PROV_DIAGNOSIS,
FLD_FOLL_UP_PROV_EXM_REASON,
INIT_FUP_CLINIC_CODE,
INIT_FUP_CLOSED_DT,
INIT_FUP_INITIAL_FOLL_UP,
INIT_FUP_INITIAL_FOLL_UP_CD,
INIT_FUP_INTERNET_FOLL_UP_CD,
INIT_FOLL_UP_NOTIFIABLE,
INIT_FUP_NOTIFIABLE_CD,
INITIATING_AGNCY,
INTERNET_FOLL_UP,
INVESTIGATION_KEY,
OOJ_AGENCY,
OOJ_DUE_DATE,
OOJ_INITG_AGNCY_OUTC_DUE_DATE,
OOJ_INITG_AGNCY_OUTC_SNT_DATE,
OOJ_INITG_AGNCY_RECD_DATE,
OOJ_NUMBER,
PAT_INTV_STATUS_CD,
STATUS_900,
SURV_CLOSED_DT,
SURV_INVESTIGATOR_ASSGN_DT,
SURV_PATIENT_FOLL_UP,
SURV_PATIENT_FOLL_UP_CD,
SURV_PROV_EXM_REASON,
SURV_PROVIDER_CONTACT,
SURV_PROVIDER_CONTACT_CD,
SURV_PROVIDER_DIAGNOSIS,
SURV_PROVIDER_EXAM_REASON
FROM S_CASE_MANAGEMENT;
QUIT;
DATA S_CASE_MANAGEMENT;
SET S_CASE_MANAGEMENT;
DROP CASE_MANAGEMENT_UID PUBLIC_HEALTH_CASE_UID;
RUN;
PROC SQL;
DROP TABLE NBS_RDB.D_CASE_MANAGEMENT;
CREATE TABLE NBS_RDB.D_CASE_MANAGEMENT AS SELECT 
ACT_REF_TYPE_CD,
ADD_USER_ID,
ADI_900_STATUS_CD,
ADI_COMPLEXION,
ADI_EHARS_ID,
ADI_HAIR,
ADI_HEIGHT,
ADI_HEIGHT_LEGACY_CASE,
ADI_OTHER_IDENTIFYING_INFO,
ADI_SIZE_BUILD,
CA_INIT_INTVWR_ASSGN_DT,
CA_INTERVIEWER_ASSIGN_DT,
CA_PATIENT_INTV_STATUS,
CASE_OID,
CASE_REVIEW_STATUS,
CASE_REVIEW_STATUS_DATE,
CC_CLOSED_DT,
D_CASE_MANAGEMENT_KEY,
EPI_LINK_ID,
FIELD_FOLL_UP_OOJ_OUTCOME,
FL_FUP_ACTUAL_REF_TYPE,
FL_FUP_DISPO_DT,
FL_FUP_DISPOSITION_CD,
FL_FUP_DISPOSITION_DESC,
FL_FUP_EXAM_DT,
FL_FUP_EXPECTED_DT,
FL_FUP_EXPECTED_IN_IND,
FL_FUP_FIELD_RECORD_NUM,
FL_FUP_INIT_ASSGN_DT,
FL_FUP_INTERNET_OUTCOME,
FL_FUP_INTERNET_OUTCOME_CD,
FL_FUP_INVESTIGATOR_ASSGN_DT,
FL_FUP_NOTIFICATION_PLAN_CD,
FL_FUP_OOJ_OUTCOME,
FL_FUP_PROV_DIAGNOSIS,
FL_FUP_PROV_EXM_REASON,
FLD_FOLL_UP_EXPECTED_IN,
FLD_FOLL_UP_NOTIFICATION_PLAN,
FLD_FOLL_UP_PROV_DIAGNOSIS,
FLD_FOLL_UP_PROV_EXM_REASON,
INIT_FUP_CLINIC_CODE,
INIT_FUP_CLOSED_DT,
INIT_FUP_INITIAL_FOLL_UP,
INIT_FUP_INITIAL_FOLL_UP_CD,
INIT_FUP_INTERNET_FOLL_UP_CD,
INIT_FOLL_UP_NOTIFIABLE,
INIT_FUP_NOTIFIABLE_CD,
INITIATING_AGNCY,
INTERNET_FOLL_UP,
INVESTIGATION_KEY,
OOJ_AGENCY,
OOJ_DUE_DATE,
OOJ_INITG_AGNCY_OUTC_DUE_DATE,
OOJ_INITG_AGNCY_OUTC_SNT_DATE,
OOJ_INITG_AGNCY_RECD_DATE,
OOJ_NUMBER,
PAT_INTV_STATUS_CD,
STATUS_900,
SURV_CLOSED_DT,
SURV_INVESTIGATOR_ASSGN_DT,
SURV_PATIENT_FOLL_UP,
SURV_PATIENT_FOLL_UP_CD,
SURV_PROV_EXM_REASON,
SURV_PROVIDER_CONTACT,
SURV_PROVIDER_CONTACT_CD,
SURV_PROVIDER_DIAGNOSIS,
SURV_PROVIDER_EXAM_REASON
FROM S_CASE_MANAGEMENT;
QUIT;
PROC DATASETS LIB=WORK MEMTYPE=DATA
		KILL;
RUN;
QUIT; 
%mend CASE_MANAGEMENT;

PROC SQL;
CREATE TABLE STD_CHECKER_MASTER_LAST 
(COUNTSTD NUM);
INSERT INTO STD_CHECKER_MASTER_LAST( COUNTSTD) VALUES 
(NULL);
UPDATE STD_CHECKER_MASTER_LAST SET COUNTSTD= (select  count(*) from NBS_ODS.case_management);
QUIT;

DATA _null_;
  set STD_CHECKER_MASTER_LAST;
  if COUNTSTD>0  then call execute('%CASE_MANAGEMENT');
RUN;

 
